### ISSUE TITLE
Back arrow not working in the movie details screen.

### ISSUE THREAD

**Issue by michaldrabik** [skydoves/DisneyMotions#1]
Just noticed small bug. Back arrow click is doing nothing in the movie details page. 
Tested on Android Emulator Nexus 5 API 23

Cheers.

**Comment by skydoves** [comment]
Thank you for your issue :)
I checked and it will be fixed soon 😁

**Comment by skydoves** [comment]
It is resolved on a679a34.
Thank you for your issue :)
