### ISSUE TITLE
Type mismatch required LiveData<TypeVariable(T)> found Unit

### ISSUE THREAD

**Issue by abdulmalekDery** [skydoves/DisneyMotions#4]
I'm trying to understanding this architecture by coding example and I followed the project set up
till I stuck with that compile time error 
  
`Type mismatch required LiveData<TypeVariable(T)> found Unit`

in the viewModel I have code like that for register request

     fun postRegisterRequest(request: RegisterRequest) {
        this.registerLiveData =  launchOnViewModelScope {
                this.authRepository.postRegister ({ s -> this.toastLiveData.postValue(s) },
                    request
                )
            }
    }

in the repository I have the following code

    suspend fun postRegister(error: (String) -> Unit, request: RegisterRequest) = withContext(Dispatchers.IO) {
        val liveData = MutableLiveData<ResponseWrapper<RegisterResponse>>()
        isLoading = true
        networkClient.postRegister( { response ->
            isLoading = false
            when (response) {
                is ApiResponse.Success -> {
                    response.data.whatIfNotNull {
                        liveData.postValue(it)
                    }
                }
                is ApiResponse.Failure.Error -> error(response.message())
                is ApiResponse.Failure.Exception -> error(response.message())
            }
        },request)
    }

the network client request look like that

     fun postRegister(
        onResult: (response: ApiResponse<ResponseWrapper<RegisterResponse>>) -> Unit,
        request: RegisterRequest
    ) {
        this.authService.register(request).transform(onResult)
    }

the authService code 

      @POST(Urls.REGISTER)
    fun register(@Body request: RegisterRequest): Call<ResponseWrapper<RegisterResponse>>

what I did wrong and how to make postRegister in the repository return  LiveData<TypeVariable(T)> instead of Unit

**Comment by skydoves** [comment]
@abdulmalekDery 
Hi, you can return the `liveData` in the coroutines context.
```kotlin
suspend fun postRegister(error: (String) -> Unit, request: RegisterRequest) = withContext(Dispatchers.IO) {
    val liveData = MutableLiveData<ResponseWrapper<RegisterResponse>>()
    return liveData
}
```

**Comment by abdulmalekDery** [comment]
thanks I will try that
