### ISSUE TITLE
Animation does not start

### ISSUE THREAD

**Issue by cleverSheep** [skydoves/DisneyMotions#6]
- Affected Device(s) [Pixel 3A API 28]
 
**Describe the Bug:**

The navigation works when clicking a movie, but the animation does doesn't. This only occurs on API 28. I've tested API 29, 27, 26; all of which work fine.

**Expected Behavior:**

Clicking on a movie should should start the material transform animation.

**Comment by skydoves** [comment]
Hi, sorry for the late reply.
I think this issue should be registered [here](https://github.com/material-components/material-components-android).
Thanks!
